### PR TITLE
Docs migration from GitBook > GitHub README

### PR DESCRIPTION
**Pull request by cwarnermm**

### CODE REVIEW

**Review by mickmister — APPROVED** [review]

**Comment by cwarnermm** [comment]
@mickmister - This PR appears stuck at the check stage. Is there a way to get it moving again?

**Comment by cwarnermm** [comment]
@mickmister - This PR appears stuck on some outstanding checks. Is there something I can do to get this ready for merge?

**Comment by mickmister** [comment]
@toninis Any idea why the CI workflows here are stuck at `Expected — Waiting for status to be reported`?

**Comment by toninis** [comment]
> /update-branch

CI was disabled due to inactivity for 60 days 🙄

**Comment by mickmister** [comment]
@toninis A similar issue is occurring on these PRs
https://github.com/mattermost/mattermost-plugin-nagios/pull/46
https://github.com/mattermost/mattermost-plugin-bitbucket/pull/119

**Pull request merged**
